// Sample/demo portfolio data used when user is not authenticated
export const DEMO_PROJECTS = [
  {
    _id: "demo1" as any,
    userId: "demo" as any,
    name: "AI-Powered Task Manager",
    description: "A smart task management app with AI-powered prioritization and scheduling",
    category: "Web Development",
    languages: ["TypeScript", "React"],
    topics: ["ai", "productivity", "web-app"],
    stars: 45,
    forks: 12,
    url: "https://github.com/nytsoul/ai-task-manager",
    featured: true,
    lastUpdated: Date.now(),
  },
  {
    _id: "demo2" as any,
    userId: "demo" as any,
    name: "Secure Chat Application",
    description: "End-to-end encrypted chat with modern security practices",
    category: "Cybersecurity",
    languages: ["Python", "JavaScript"],
    topics: ["security", "encryption", "chat"],
    stars: 38,
    forks: 8,
    url: "https://github.com/nytsoul/secure-chat",
    featured: true,
    lastUpdated: Date.now(),
  },
  {
    _id: "demo3" as any,
    userId: "demo" as any,
    name: "ML Model Optimizer",
    description: "Optimize and compress machine learning models for production deployment",
    category: "Machine Learning",
    languages: ["Python"],
    topics: ["machine-learning", "optimization", "tensorflow"],
    stars: 52,
    forks: 15,
    url: "https://github.com/nytsoul/ml-optimizer",
    featured: true,
    lastUpdated: Date.now(),
  },
  {
    _id: "demo4" as any,
    userId: "demo" as any,
    name: "DevOps Automation Framework",
    description: "Automated deployment and infrastructure management framework",
    category: "DevOps",
    languages: ["Go", "Python"],
    topics: ["devops", "automation", "kubernetes"],
    stars: 28,
    forks: 7,
    url: "https://github.com/nytsoul/devops-framework",
    featured: false,
    lastUpdated: Date.now(),
  },
];

export const DEMO_SKILLS = [
  {
    _id: "skill1" as any,
    userId: "demo" as any,
    name: "TypeScript",
    category: "Languages",
    strength: 95,
    usageCount: 50,
    lastUsed: Date.now(),
  },
  {
    _id: "skill2" as any,
    userId: "demo" as any,
    name: "React",
    category: "Frameworks",
    strength: 90,
    usageCount: 45,
    lastUsed: Date.now(),
  },
  {
    _id: "skill3" as any,
    userId: "demo" as any,
    name: "Python",
    category: "Languages",
    strength: 85,
    usageCount: 40,
    lastUsed: Date.now(),
  },
  {
    _id: "skill4" as any,
    userId: "demo" as any,
    name: "Node.js",
    category: "Frameworks",
    strength: 88,
    usageCount: 38,
    lastUsed: Date.now(),
  },
  {
    _id: "skill5" as any,
    userId: "demo" as any,
    name: "Docker",
    category: "Tools",
    strength: 82,
    usageCount: 30,
    lastUsed: Date.now(),
  },
  {
    _id: "skill6" as any,
    userId: "demo" as any,
    name: "MongoDB",
    category: "Databases",
    strength: 80,
    usageCount: 28,
    lastUsed: Date.now(),
  },
];

export const DEMO_ACHIEVEMENTS = [
  {
    _id: "ach1" as any,
    userId: "demo" as any,
    title: "Projects Completed",
    value: "25+",
    description: "Successfully completed various projects",
    order: 1,
  },
  {
    _id: "ach2" as any,
    userId: "demo" as any,
    title: "GitHub Stars",
    value: "500+",
    description: "Total stars across all repositories",
    order: 2,
  },
  {
    _id: "ach3" as any,
    userId: "demo" as any,
    title: "Contributors",
    value: "100+",
    description: "Community contributions and collaborations",
    order: 3,
  },
];
