// Sample/demo portfolio data used when user is not authenticated
export const DEMO_PROJECTS = [
  {
    _id: 'demo1',
    userId: 'demo',
    name: 'Agroverse',
    description: 'Transparent in supply chain',
    category: 'Web Development',
    languages: ['TypeScript'],
    topics: ['supply-chain', 'transparency', 'blockchain'],
    stars: 0,
    forks: 0,
    url: 'https://github.com/nytsoul/Agroverse',
    featured: true,
    lastUpdated: new Date(),
  },
  {
    _id: 'demo2',
    userId: 'demo',
    name: 'SmartLearnApp',
    description: '1-12 Student learning platform with intelligent features',
    category: 'Mobile Development',
    languages: ['TypeScript'],
    topics: ['education', 'learning', 'mobile'],
    stars: 0,
    forks: 0,
    url: 'https://github.com/nytsoul/SmartLearnApp',
    featured: true,
    lastUpdated: new Date(),
  },
  {
    _id: 'demo3',
    userId: 'demo',
    name: 'SoulLink',
    description: 'Dual Mode Selection application',
    category: 'Web Development',
    languages: ['TypeScript'],
    topics: ['communication', 'dual-mode', 'web-app'],
    stars: 0,
    forks: 0,
    url: 'https://github.com/nytsoul/SoulLink',
    featured: true,
    lastUpdated: new Date(),
  },
  {
    _id: 'demo4',
    userId: 'demo',
    name: 'Portfolio',
    description: 'Personal portfolio website showcasing projects and skills',
    category: 'Web Development',
    languages: ['TypeScript'],
    topics: ['portfolio', 'react', 'typescript'],
    stars: 0,
    forks: 0,
    url: 'https://github.com/nytsoul/Portfolio',
    featured: true,
    lastUpdated: new Date(),
  },
  {
    _id: 'demo5',
    userId: 'demo',
    name: 'Personal',
    description: 'Notes writing app with rich features',
    category: 'Mobile Development',
    languages: ['Dart'],
    topics: ['notes', 'flutter', 'productivity'],
    stars: 0,
    forks: 0,
    url: 'https://github.com/nytsoul/Personal',
    featured: false,
    lastUpdated: new Date(),
  },
  {
    _id: 'demo6',
    userId: 'demo',
    name: 'Algorithms-platform',
    description: 'Platform to learn Data Structures and Algorithms',
    category: 'Competitive Programming',
    languages: ['Dart'],
    topics: ['algorithms', 'dsa', 'learning'],
    stars: 0,
    forks: 0,
    url: 'https://github.com/nytsoul/Algorithms-plateform',
    featured: false,
    lastUpdated: new Date(),
  },
];

export const DEMO_SKILLS = [
  // Programming Languages
  {
    _id: 'skill1',
    userId: 'demo',
    name: 'TypeScript',
    category: 'Languages',
    strength: 95,
    usageCount: 4,
    lastUsed: new Date(),
    icon: '🔷',
  },
  {
    _id: 'skill2',
    userId: 'demo',
    name: 'JavaScript',
    category: 'Languages',
    strength: 92,
    usageCount: 4,
    lastUsed: new Date(),
    icon: '⚡',
  },
  {
    _id: 'skill3',
    userId: 'demo',
    name: 'Python',
    category: 'Languages',
    strength: 85,
    usageCount: 3,
    lastUsed: new Date(),
    icon: '🐍',
  },
  {
    _id: 'skill4',
    userId: 'demo',
    name: 'Java',
    category: 'Languages',
    strength: 82,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '☕',
  },
  {
    _id: 'skill5',
    userId: 'demo',
    name: 'C',
    category: 'Languages',
    strength: 80,
    usageCount: 2,
    lastUsed: new Date(),
    icon: 'C',
  },
  {
    _id: 'skill6',
    userId: 'demo',
    name: 'Dart',
    category: 'Languages',
    strength: 88,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '🎯',
  },
  {
    _id: 'skill7',
    userId: 'demo',
    name: 'HTML5',
    category: 'Languages',
    strength: 93,
    usageCount: 4,
    lastUsed: new Date(),
    icon: '📄',
  },
  {
    _id: 'skill8',
    userId: 'demo',
    name: 'CSS3',
    category: 'Languages',
    strength: 91,
    usageCount: 4,
    lastUsed: new Date(),
    icon: '🎨',
  },
  // Frontend Development Tools
  {
    _id: 'skill9',
    userId: 'demo',
    name: 'React',
    category: 'Tools',
    strength: 93,
    usageCount: 4,
    lastUsed: new Date(),
    icon: '⚛️',
  },
  {
    _id: 'skill10',
    userId: 'demo',
    name: 'Next.js',
    category: 'Tools',
    strength: 88,
    usageCount: 2,
    lastUsed: new Date(),
    icon: 'N',
  },
  {
    _id: 'skill11',
    userId: 'demo',
    name: 'Tailwind CSS',
    category: 'Tools',
    strength: 85,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '🌊',
  },
  // Backend Development Tools
  {
    _id: 'skill12',
    userId: 'demo',
    name: 'Node.js',
    category: 'Tools',
    strength: 85,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '🟢',
  },
  {
    _id: 'skill13',
    userId: 'demo',
    name: 'Express.js',
    category: 'Tools',
    strength: 83,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '⚙️',
  },
  {
    _id: 'skill14',
    userId: 'demo',
    name: 'REST APIs',
    category: 'Tools',
    strength: 88,
    usageCount: 4,
    lastUsed: new Date(),
    icon: '🔌',
  },
  {
    _id: 'skill15',
    userId: 'demo',
    name: 'Mongoose',
    category: 'Tools',
    strength: 82,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '🦁',
  },
  {
    _id: 'skill16',
    userId: 'demo',
    name: 'Firebase',
    category: 'Tools',
    strength: 82,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '🔥',
  },
  // Mobile App Development Tools
  {
    _id: 'skill17',
    userId: 'demo',
    name: 'Flutter (Dart)',
    category: 'Tools',
    strength: 87,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '🦋',
  },
  {
    _id: 'skill18',
    userId: 'demo',
    name: 'React Native',
    category: 'Tools',
    strength: 80,
    usageCount: 1,
    lastUsed: new Date(),
    icon: '📱',
  },
  // Databases Tools
  {
    _id: 'skill19',
    userId: 'demo',
    name: 'MongoDB',
    category: 'Tools',
    strength: 80,
    usageCount: 2,
    lastUsed: new Date(),
    icon: '🍃',
  },
  {
    _id: 'skill20',
    userId: 'demo',
    name: 'PostgreSQL',
    category: 'Tools',
    strength: 78,
    usageCount: 1,
    lastUsed: new Date(),
    icon: '🐘',
  },
  // DevOps & Tools
  {
    _id: 'skill21',
    userId: 'demo',
    name: 'Git',
    category: 'Tools',
    strength: 94,
    usageCount: 6,
    lastUsed: new Date(),
    icon: '📦',
  },
  {
    _id: 'skill22',
    userId: 'demo',
    name: 'GitHub',
    category: 'Tools',
    strength: 94,
    usageCount: 6,
    lastUsed: new Date(),
    icon: '🐙',
  },
  {
    _id: 'skill23',
    userId: 'demo',
    name: 'Docker',
    category: 'Tools',
    strength: 75,
    usageCount: 1,
    lastUsed: new Date(),
    icon: '🐳',
  },
];

export const DEMO_ACHIEVEMENTS = [
  {
    _id: 'ach1',
    userId: 'demo',
    title: 'Projects Completed',
    value: '25+',
    description: 'Successfully completed various projects',
    icon: '🚀',
    order: 1,
  },
  {
    _id: 'ach2',
    userId: 'demo',
    title: 'GitHub Stars',
    value: '500+',
    description: 'Total stars across all repositories',
    icon: '⭐',
    order: 2,
  },
  {
    _id: 'ach3',
    userId: 'demo',
    title: 'Contributors',
    value: '100+',
    description: 'Community contributions and collaborations',
    icon: '👥',
    order: 3,
  },
  {
    _id: 'ach4',
    userId: 'demo',
    title: 'Smart India Hackathon',
    value: 'Finalist',
    description: 'Selected as finalist in Smart India Hackathon 2024',
    icon: '🏆',
    order: 4,
  },
];
